#!/bin/bash
#
# Fails the build when a .swift file on disk is missing from the generated
# Xcode project.
#
# StartKind.xcodeproj is generated by XcodeGen from project.yml and is
# gitignored, so it is never committed. project.yml globs the whole StartKind
# directory, which means a newly added file is picked up *when XcodeGen runs* -
# and nothing runs it automatically. A file added after the last generate is
# simply absent from the build.
#
# That failure is silent and expensive: a source file appears to compile
# because nothing references it, and, worse, a test file that is not in the
# project reports "TEST SUCCEEDED" while executing zero tests. This check turns
# that into a loud build error naming the file and the fix.
set -euo pipefail

ROOT="${SRCROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
PBXPROJ="$ROOT/StartKind.xcodeproj/project.pbxproj"

if [ ! -f "$PBXPROJ" ]; then
    echo "error: $PBXPROJ not found. Run: xcodegen generate"
    exit 1
fi

missing=()
while IFS= read -r file; do
    name="$(basename "$file")"
    # Plain substring match: XcodeGen writes each file as `path = Name.swift;`
    # and basenames are unique across this project.
    if ! grep -qF "$name" "$PBXPROJ"; then
        missing+=("${file#"$ROOT"/}")
    fi
done < <(find "$ROOT/StartKind" "$ROOT/StartKindTests" "$ROOT/StartKindUITests" -name '*.swift' -type f 2>/dev/null)

if [ ${#missing[@]} -gt 0 ]; then
    echo "error: ${#missing[@]} Swift file(s) exist on disk but are not in StartKind.xcodeproj."
    echo "error: They are NOT being built. A test file in this state reports success while running zero tests."
    for f in "${missing[@]}"; do
        echo "error:   $f"
    done
    echo "error: Fix: cd $ROOT && xcodegen generate"
    exit 1
fi
